version: '3'
name: nginx
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    networks:
      - media-stack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/emerson/.netflox/media-stack/conf.d:/config/nginx/site-confs
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  media-stack:
    external: true
