version: '2'
name: nginx
services:
  nginx:
    image: jc21/nginx-proxy-manager
    container_name: nginx
    networks:
      - media-stack_mynetwork
    volumes:
      - /home/emerson/.netflox/nginx/nginx.config:/etc/nginx/conf.d/default.conf:ro
      - /home/emerson/.netflox/nginx/data:/data
      - /home/emerson/.netflox/nginx/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 81:81
      - 443:443
    restart: unless-stopped

networks:
  media-stack_mynetwork:
    external: true
